const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  WISHLIST: '/wishlist',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  SELLER_DASHBOARD: '/seller/dashboard',
  SELLER_PRODUCTS: '/seller/products',
  SELLER_CREATE_PRODUCT: '/seller/products/create',
  SELLER_EDIT_PRODUCT: '/seller/products/:id/edit',
  SELLER_ORDERS: '/seller/orders',
  SELLER_ANALYTICS: '/seller/analytics',
  SELLER_PAYOUTS: '/seller/payouts',
  SELLER_REGISTER: '/seller/register',
  SELLER_SHOP: '/seller/:shopId',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_MODERATION: '/admin/moderation',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_SETTINGS: '/admin/settings',
  SUPPORT: '/support',
  CONTACT: '/contact',
  ABOUT: '/about',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  COOKIES: '/cookies',
  NOT_FOUND: '/404',
  MAINTENANCE: '/maintenance',
  UNAUTHORIZED: '/unauthorized',
};

export default ROUTES;
