export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: 'En attente',
  [ORDER_STATUS.CONFIRMED]: 'Confirmée',
  [ORDER_STATUS.SHIPPED]: 'Expédiée',
  [ORDER_STATUS.DELIVERED]: 'Livrée',
  [ORDER_STATUS.CANCELLED]: 'Annulée',
  [ORDER_STATUS.REFUNDED]: 'Remboursée',
};

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.PENDING]: '#f59e0b',
  [ORDER_STATUS.CONFIRMED]: '#3b82f6',
  [ORDER_STATUS.SHIPPED]: '#8b5cf6',
  [ORDER_STATUS.DELIVERED]: '#10b981',
  [ORDER_STATUS.CANCELLED]: '#ef4444',
  [ORDER_STATUS.REFUNDED]: '#6b7280',
};

export const PRODUCT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  ARCHIVED: 'ARCHIVED',
};

export const PRODUCT_STATUS_LABELS = {
  [PRODUCT_STATUS.DRAFT]: 'Brouillon',
  [PRODUCT_STATUS.PENDING]: 'En attente',
  [PRODUCT_STATUS.ACTIVE]: 'Actif',
  [PRODUCT_STATUS.SUSPENDED]: 'Suspendu',
  [PRODUCT_STATUS.ARCHIVED]: 'Archivé',
};

export const PRODUCT_STATUS_COLORS = {
  [PRODUCT_STATUS.DRAFT]: '#6b7280',
  [PRODUCT_STATUS.PENDING]: '#f59e0b',
  [PRODUCT_STATUS.ACTIVE]: '#10b981',
  [PRODUCT_STATUS.SUSPENDED]: '#ef4444',
  [PRODUCT_STATUS.ARCHIVED]: '#9ca3af',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BANNED: 'BANNED',
};

export const USER_STATUS_LABELS = {
  [USER_STATUS.ACTIVE]: 'Actif',
  [USER_STATUS.INACTIVE]: 'Inactif',
  [USER_STATUS.BANNED]: 'Banni',
};

export const USER_STATUS_COLORS = {
  [USER_STATUS.ACTIVE]: '#10b981',
  [USER_STATUS.INACTIVE]: '#f59e0b',
  [USER_STATUS.BANNED]: '#ef4444',
};
